from typing import TypedDict, List, Dict, Any, Optional


class ModernizationState(TypedDict, total=False):
    """
    Global shared state passed across workflow nodes.

    Phase 4: Extends Phase 3 with advanced planning, risk, semantic, and transformation tracking fields.
    All nodes read/write only through this structure to avoid
    hidden dependencies and unpredictable behaviour.

    Flow:
        parser → analyzer → planner → modernizer → semantic_guard → verifier → fixer
    """
    # ========================
    # PHASE 4 EXTENSIONS
    # ========================

    modernization_plan: Dict[str, Any]
    """
    Plan generated by planner node.
    Example:
    {
        "target_functions": ["createNode", "deleteNode"],
        "target_types": ["Node"],
        "priority_order": ["Node", "createNode"],
        "strategy": "ownership_safe"
    }
    """

    risk_report: Dict[str, Any]
    """
    Risk analysis for planned transformations.
    Example:
    {
        "overall_risk": 0.42,
        "high_risk_items": ["pointer_alias"],
        "notes": ["raw pointer ownership unclear"]
    }
    """

    semantic_report: Dict[str, Any]
    """
    Semantic understanding of code structure.
    Example:
    {
        "ownership_detected": True,
        "const_correctness": False,
        "pointer_mutation": False,
        "lifetime_patterns": ["factory_return"]
    }
    """

    semantic_ok: bool
    """
    True if semantic_guard confirms behavior invariants preserved.
    """

    dependency_graph: Dict[str, Any]
    """
    Graph representation of relationships.
    Example:
    {
        "createNode": ["Node"],
        "deleteNode": ["Node"],
        "Node": ["Node*"]
    }
    """

    transformation_log: List[Dict[str, Any]]
    """
    History of applied transformations.
    Example:
    [
        {
            "rule": "malloc_to_unique_ptr",
            "location": "createNode",
            "risk": "medium"
        }
    ]
    """

    planner_feedback: Dict[str, Any]
    """
    Feedback from verifier/semantic_guard to planner.
    Example:
    {
        "avoid_patterns": ["ownership_change"],
        "reduce_scope": True
    }
    """

    # ========================
    # SOURCE INPUT
    # ========================

    code: str
    """
    Original legacy source code.
    Never mutated after initialization.
    """

    modernized_code: str
    """
    Latest transformed version of the code.
    Each node updates this value.
    """

    output_code: str
    """
    Final verified code that is safe to write to disk.
    """

    original_file_path: str
    """
    Path of input file.
    Used for logging and compiler diagnostics.
    """

    output_file_path: str
    """
    Path where final modernized code will be written.
    """

    language: str
    """
    Target C++ standard.
    Default: c++17
    """

    # ========================
    # ANALYSIS RESULTS
    # ========================

    functions_info: List[Dict[str, Any]]
    """
    Extracted function metadata.

    Example:
    [
        {
            "name": "createNode",
            "start_line": 10,
            "end_line": 42
        }
    ]
    """

    modernization_targets: List[Dict[str, Any]]
    """
    Identified modernization opportunities.

    Example:
    [
        {
            "type": "malloc",
            "line": 21,
            "confidence": 0.95
        }
    ]
    """

    original_function_signatures: Dict[str, str]
    """
    Function signature backup for validation.

    Example:
        {
            "createNode": "Node* createNode(int id)"
        }
    """

    original_structure_snapshot: Dict[str, Any]
    """
    Snapshot of original file structure for safety checks.
    """

    # ========================
    # LOOP CONTROL
    # ========================

    attempt_count: int
    """
    Total modernization attempts.
    Prevents infinite loops.
    """

    feedback_loop_count: int
    """
    Number of fixer attempts.
    """

    last_working_code: str
    """
    Backup copy used for rollback if a fix fails.
    """

    modernized_functions: List[str]
    """
    Track which functions were successfully transformed.
    """

    # ========================
    # VERIFICATION
    # ========================

    verification_result: Dict[str, Any]
    """
    Compiler/test result.

    Example:
    {
        "compiled": True,
        "ran": True,
        "exit_code": 0
    }
    """

    error_log: str
    """
    Latest compiler or runtime error.
    """

    # ========================
    # RUNTIME CONTEXT
    # ========================

    context: Any
    """
    WorkflowContext instance.
    Contains config, paths, model settings.
    """

    metrics: Dict[str, Any]
    """
    Execution statistics.

    Example:
        {
            "tokens_used": 0,
            "transformations_applied": 5
        }
    """

    modernization_strategy: str
    """
    Strategy for applying transformations.

    allowed:
        function_level
        full_file
    """

    modernization_mode: str
    """
    Controls safety level.

    allowed:
        safe        -> only guaranteed-safe rules
        balanced    -> moderate transformations
    """

    developer_feedback: str
    """
    Natural-language feedback injected between modernization retry passes.
    Set by semantic_guard when legacy patterns (malloc, free, etc.) survive
    in the output. The next modernizer pass reads this to know what to fix.
    """

    project_map: Dict[str, Any]
    """
    AST-level map produced by CppParser: functions, types, includes, etc.
    """

    extra_compile_args: List[str]
    """
    Additional compiler flags forwarded from the API request (extra_flags).
    """

    plan_summary: str
    """
    Human-readable summary of the modernization plan.
    """

    legacy_findings: List[str]
    """
    List of detected legacy patterns from the analyzer node.
    """

    has_implementation: bool
    """
    True when this is a header file that has a corresponding .cpp file.
    The modernizer uses this to avoid inlining method bodies.
    """

    header_code: str
    """
    Modernized declarations from a paired header file, passed to the
    modernizer so it can match method signatures.
    """

    pipeline_metadata: Dict[str, Any]
    """
    Diagnostic metadata emitted by the modernizer node (which layers ran,
    whether chunked processing was used, etc.).
    """

    request_id: str
    """
    Unique request identifier for structured logging correlation.
    """

    run_id: str
    """
    Database run ID for structured logging correlation.
    """



def create_initial_state(
    code: str,
    language: str = "c++17",
    source_file: str = "",
    output_file_path: str = "",
    context: Optional[Any] = None,
    request_id: str = "",
    run_id: str = "",
) -> ModernizationState:
    """
    Creates a fully initialized workflow state.

    Ensures all expected keys exist so nodes never fail
    due to missing state values.

    Safe defaults are chosen for Phase 3 stability.
    """

    # lazy import to avoid circular dependency
    if context is None:
        try:
            from agents.workflow.context import WorkflowContext
            context = WorkflowContext()
        except Exception:
            context = None

    return ModernizationState(
        # source
        code=code or "",
        modernized_code=code or "",
        output_code="",

        original_file_path=source_file or "",
        output_file_path=output_file_path or "",

        language=language or "c++17",

        # analysis
        functions_info=[],
        modernization_targets=[],
        original_function_signatures={},
        original_structure_snapshot={},
        legacy_findings=[],
        project_map={},

        # PHASE 4 EXTENSIONS (safe defaults)
        modernization_plan={},
        risk_report={},
        semantic_report={},
        semantic_ok=True,
        dependency_graph={},
        transformation_log=[],
        planner_feedback={},
        plan_summary="",
        pipeline_metadata={},

        # retry / feedback
        developer_feedback="",

        # control
        attempt_count=0,
        feedback_loop_count=0,
        last_working_code=code or "",
        modernized_functions=[],

        # verification
        verification_result={},
        error_log="",

        # runtime
        context=context,
        metrics={},
        extra_compile_args=[],

        # configuration
        modernization_strategy="function_level",
        modernization_mode="safe",

        # header-aware modernization
        has_implementation=False,
        header_code="",
        
        request_id=request_id or "",
        run_id=run_id or "",
    )